### ISSUE TITLE
Broken link in Readme.md

### ISSUE THREAD

**Issue by ipr0310** [deleterium/SmartC#13]
![image](https://user-images.githubusercontent.com/35440957/142764197-20fe7ac9-5d48-4993-8f7e-5b5f6146850f.png)
That link redirects to a page which does not exists

**Comment by deleterium** [comment]
@ipr0310  Thanks for reporting. I updated description to inform that all documentation is inside compiler's page. Commit [4c19e71](https://github.com/deleterium/SmartC/commit/4c19e71e02a4cd5db9dab43eeb747c4bc464f1ef) fixed it!
