### ISSUE TITLE
An idea for a new logo

### ISSUE THREAD

**Issue by rever273** [deleterium/SmartC#8]
![SmartC Logo2](https://user-images.githubusercontent.com/77928665/139755358-b4f90e36-065c-44c3-999a-a8555304cb6f.png)
![SmartC Logo7](https://user-images.githubusercontent.com/77928665/139755361-880ea435-690c-4fea-8d2c-ee10eae31ccb.png)
![SmartC Logo1](https://user-images.githubusercontent.com/77928665/139755362-8b4b9b24-638e-45d4-936c-1c674ccd0e43.png)

I suggest using one of this logo for the program.

**Comment by deleterium** [comment]
Very good!!!

**Comment by deleterium** [comment]
@rever273 Thank you very much for the ideas. Please check PR #11 with changes and inspect preview at https://smart-c-git-newlogo-deleterium.vercel.app/

**Comment by deleterium** [comment]
Thank you very much @rever273 ! Your logo and a new website theme were merged into main!
